apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api//config/default?ref=v1.10.10
images:
  - name: controller
    newName: registry.k8s.io/cluster-api/cluster-api-controller
    newTag: v1.12.2
