apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm//config/default?ref=v0.4.2
images:
  - name: controller
    newName: registry.k8s.io/cluster-api-helm/cluster-api-helm-controller
    newTag: v0.6.0
