apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.0/manifests/install.yaml
  - routes/httproute.yaml
  - routes/certificate.yaml
  - routes/backend-tls-policy.yaml
  - routes/networkpolicy.yaml

patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/resource-limits.yaml

