apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/siderolabs/cluster-api-control-plane-provider-talos//config/default?ref=v0.5.12
images:
  - name: controller
    newName: ghcr.io/siderolabs/cluster-api-control-plane-talos-controller
    newTag: v0.5.12
