apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/siderolabs/cluster-api-bootstrap-provider-talos//config/default?ref=v0.6.11
images:
  - name: controller
    newName: ghcr.io/siderolabs/cluster-api-talos-controller
    newTag: v0.6.11
